
server:
  port: 8109

#\u5E94\u7528\u540D\u79F0
spring:
  application:
    name: service-spring
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 1
    max-active: 20
    max-open-prepared-statements: 20
    maxWait: 60000
    min-evictable-idle-time-millis: 300000
    min-idle: 5
    password: 123456
    pool-prepared-statements: false
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    #&allowMultiQueries=true \u4F7F\u7528\u6279\u91CF\u65B0\u589E\u65F6\uFF0C\u6570\u636E\u5E93\u8FDE\u63A5Url\u5FC5\u987B\u52A0\u4E0A\u5141\u8BB8\u6279\u91CF\u64CD\u4F5C\uFF0C\u4E0D\u7136\u4F1A\u6709sql\u5F02\u5E38\u629B\u51FA
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    validation-query: SELECT 'x'
dubbo:
  application:
    name: customer-service
    qosEnable: false
    qosPort: 22223
    qosAcceptForeignIp: false
  registry:   #
    address:  zookeeper://127.0.0.1:2181
   # address: zookeeper://192.168.128.13:2181?backup=192.168.128.24:2181,192.168.128.25:2181
#\u66B4\u9732\u670D\u52A1\u65B9\u5F0F
  protocol:
    name: dubbo
    port: 20880
  scan: com.jiessie.service.service.impl

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.jiessie.facade.domain

logging:
#  config: classpath:logback-spring-test.xml
  level:
    com:
      alibaba:
        druid: debug
      jiessie:
        service:
          mapper: debug
    org:
      mybatis: debug


